{
 "title": "Erigon Prometheus",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "tx_pool_counters",
    "label": "TxPoolCounters",
    "query": {
     "query": "{job=\"geth\"}"
    }
   },
   { "name": "job", "query": "geth" },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   },
   { "name": "instance", "label": "instance", "query": { "query": "system_cpu_sysload" } }
  ]
 },
 "panels": [
  {
   "title": "Block Execution progress",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stage_execution{instance=~\"$instance\"}",
     "legendFormat": "execution: {{instance}}"
    }
   ]
  },
  {
   "title": "Blocks Execution rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(stage_execution{instance=~\"$instance\"}[5m])",
     "legendFormat": "execution:  {{instance}}"
    }
   ]
  },
  {
   "title": "Block Execution speed (stage 5)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "chain_execution{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "execution: {{instance}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Commit",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(db_commit_big_batch_count{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "commit: {{instance}}"
    }
   ]
  },
  {
   "title": "Commit speed",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "db_commit_big_batch{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "commit: {{instance}}"
    },
    {
     "expr": "db_commit_gc{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "commit_gc: {{instance}}"
    },
    {
     "expr": "db_commit_write{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "commit_write: {{instance}}"
    },
    {
     "expr": "db_commit_sync{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "commit_sync: {{instance}}"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "db_size{instance=~\"$instance\"}",
     "legendFormat": "size: {{instance}}"
    }
   ]
  },
  {
   "title": "GC and State",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "db_gc_leaf{instance=~\"$instance\"}",
     "legendFormat": "gc_leaf: {{instance}}"
    },
    {
     "expr": "db_gc_branch{instance=~\"$instance\"}",
     "legendFormat": "gc_branch: {{instance}}"
    },
    {
     "expr": "db_state_leaf{instance=~\"$instance\"}",
     "legendFormat": "state_leaf: {{instance}}"
    },
    {
     "expr": "db_state_branch{instance=~\"$instance\"}",
     "legendFormat": "state_branch: {{instance}}"
    }
   ]
  },
  {
   "title": "DB Pages Ops/sec",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_pgops_clone{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "clone: {{instance}}"
    },
    {
     "expr": "rate(db_pgops_split{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "split: {{instance}}"
    },
    {
     "expr": "rate(db_pgops_spill{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "spill: {{instance}}"
    },
    {
     "expr": "rate(db_pgops_wops{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "wops: {{instance}}"
    },
    {
     "expr": "rate(db_pgops_unspill{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "unspill: {{instance}}"
    }
   ]
  },
  {
   "title": "Tx Size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "tx_limit{instance=~\"$instance\"}",
     "legendFormat": "limit: {{instance}}"
    },
    {
     "expr": "tx_dirty{instance=~\"$instance\"}",
     "legendFormat": "dirty: {{instance}}"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Rusage Total (\"last value\" - \"first value\" on selected period)",
   "type": "stat",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "ru_inblock{instance=~\"$instance\"}",
     "legendFormat": "inblock: {{instance}}"
    },
    {
     "expr": "ru_outblock{instance=~\"$instance\"}",
     "legendFormat": "outblock: {{instance}}"
    },
    {
     "expr": "ru_minflt{instance=~\"$instance\"}",
     "legendFormat": "minflt: {{instance}}"
    },
    {
     "expr": "ru_majflt{instance=~\"$instance\"}",
     "legendFormat": "majflt: {{instance}}"
    },
    {
     "expr": "system_disk_readbytes{instance=~\"$instance\"}",
     "legendFormat": "system_disk_readbytes: {{instance}}"
    },
    {
     "expr": "system_disk_writebytes{instance=~\"$instance\"}",
     "legendFormat": "system_disk_writebytes: {{instance}}"
    },
    {
     "expr": "db_pgops_newly{instance=~\"$instance\"}",
     "legendFormat": "pgops_newly: {{instance}}"
    },
    {
     "expr": "db_pgops_cow{instance=~\"$instance\"}",
     "legendFormat": "pgops_cow: {{instance}}"
    },
    {
     "expr": "db_pgops_clone{instance=~\"$instance\"}",
     "legendFormat": "pgops_clone: {{instance}}"
    },
    {
     "expr": "db_pgops_split{instance=~\"$instance\"}",
     "legendFormat": "pgops_split: {{instance}}"
    },
    {
     "expr": "db_pgops_merge{instance=~\"$instance\"}",
     "legendFormat": "pgops_merge: {{instance}}"
    },
    {
     "expr": "db_pgops_spill{instance=~\"$instance\"}",
     "legendFormat": "pgops_spill: {{instance}}"
    },
    {
     "expr": "db_pgops_unspill{instance=~\"$instance\"}",
     "legendFormat": "pgops_unspill: {{instance}}"
    },
    {
     "expr": "db_pgops_wops{instance=~\"$instance\"}",
     "legendFormat": "pgops_wops: {{instance}}"
    }
   ]
  },
  {
   "title": "Disk io (same as rusage.inblock/outblock)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(ru_inblock{instance=~\"$instance\"}[30s])",
     "legendFormat": "in: {{instance}}"
    },
    {
     "expr": "rate(ru_outblock{instance=~\"$instance\"}[1m])",
     "legendFormat": "out: {{instance}}"
    }
   ]
  },
  {
   "title": "getrusage: minflt - soft page faults (reclaims), majflt - hard faults",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(ru_minflt{instance=~\"$instance\"}[1m])",
     "legendFormat": "soft: {{instance}}"
    },
    {
     "expr": "rate(ru_majflt{instance=~\"$instance\"}[1m])",
     "legendFormat": "hard: {{instance}}"
    },
    {
     "expr": "rate(ru_minflt2{instance=~\"$instance\"}[1m])",
     "legendFormat": "soft2: {{instance}}"
    },
    {
     "expr": "rate(ru_majflt2{instance=~\"$instance\"}[1m])",
     "legendFormat": "hard2: {{instance}}"
    }
   ]
  },
  {
   "title": "Disk bytes/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{instance=~\"$instance\"}[1m])",
     "legendFormat": "read: {{instance}}"
    },
    {
     "expr": "rate(system_disk_writebytes{instance=~\"$instance\"}[1m])",
     "legendFormat": "write: {{instance}}"
    }
   ]
  },
  {
   "title": "getrusage: nvcsw/sec - context switch due to voluntarily giving up the processor (resource wait), nivcsw",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ru_nvcsw{instance=~\"$instance\"}[1m])",
     "legendFormat": "voluntarily: {{instance}}"
    },
    {
     "expr": "rate(ru_nivcsw{instance=~\"$instance\"}[1m])",
     "legendFormat": "involuntarily: {{instance}}"
    }
   ]
  },
  {
   "title": "Process Mem: system - obtained from OS,  alloc - allocated",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "system_memory_held{instance=~\"$instance\"}",
     "legendFormat": "system: {{instance}}"
    },
    {
     "expr": "system_memory_used{instance=~\"$instance\"}",
     "legendFormat": "alloc: {{instance}}"
    }
   ]
  },
  {
   "title": "GO Goroutines and Threads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "go/goroutines: {{instance}}"
    },
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "go/threads: {{instance}}"
    }
   ]
  },
  {
   "title": "mem: resident set size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mem_rss{instance=~\"$instance\"}",
     "legendFormat": "rss: {{instance}}"
    },
    {
     "expr": "mem_hwm{instance=~\"$instance\"}",
     "legendFormat": "hwm: {{instance}}"
    },
    {
     "expr": "mem_data{instance=~\"$instance\"}",
     "legendFormat": "data: {{instance}}"
    },
    {
     "expr": "mem_stack{instance=~\"$instance\"}",
     "legendFormat": "stack: {{instance}}"
    },
    {
     "expr": "mem_locked{instance=~\"$instance\"}",
     "legendFormat": "locked: {{instance}}"
    },
    {
     "expr": "mem_swap{instance=~\"$instance\"}",
     "legendFormat": "swap: {{instance}}"
    }
   ]
  },
  {
   "title": "GC Stop the World per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(system_memory_pauses{instance=~\"$instance\"}[1m])",
     "legendFormat": "system/memory/pauses: {{instance}}"
    }
   ]
  },
  {
   "title": "Process Mem: allocate objects/sec, free",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(system_memory_allocs{instance=~\"$instance\"}[5m])",
     "legendFormat": "alloc: {{instance}}"
    },
    {
     "expr": "rate(system_memory_frees{instance=~\"$instance\"}[5m])",
     "legendFormat": "free: {{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_sysload{instance=~\"$instance\"}",
     "legendFormat": "system: {{instance}}"
    },
    {
     "expr": "system_cpu_syswait{instance=~\"$instance\"}",
     "legendFormat": "iowait: {{instance}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Host VMem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vmem_total{instance=~\"$instance\"}",
     "legendFormat": "total: {{instance}}"
    },
    {
     "expr": "vmem_available{instance=~\"$instance\"}",
     "legendFormat": "available: {{instance}}"
    },
    {
     "expr": "vmem_used{instance=~\"$instance\"}",
     "legendFormat": "used: {{instance}}"
    },
    {
     "expr": "vmem_buffers{instance=~\"$instance\"}",
     "legendFormat": "buffers: {{instance}}"
    },
    {
     "expr": "vmem_cached{instance=~\"$instance\"}",
     "legendFormat": "cached: {{instance}}"
    },
    {
     "expr": "vmem_writeback{instance=~\"$instance\"}",
     "legendFormat": "writeback: {{instance}}"
    },
    {
     "expr": "vmem_dirty{instance=~\"$instance\"}",
     "legendFormat": "dirty: {{instance}}"
    },
    {
     "expr": "vmem_shared{instance=~\"$instance\"}",
     "legendFormat": "shared: {{instance}}"
    },
    {
     "expr": "vmem_mapped{instance=~\"$instance\"}",
     "legendFormat": "mapped: {{instance}}"
    }
   ]
  },
  { "title": "Hidden", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Merkle Root calculation (stage 5)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "trie_subtrieloader_flatdb{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "trie_subtrieloader_flatdb: {{quantile}}, {{instance}}"
    },
    {
     "expr": "trie_subtrieloader_witnessdb{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "trie_subtrieloader_witnessdb: {{quantile}}, {{instance}}"
    }
   ]
  },
  {
   "title": "AutoDupsort Call/Sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_op_set_count{instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "rate(db_op_set_range_count{instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "rate(db_op_get_count{instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "rate(db_op_get_both{instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "rate(db_op_get_both_range_count{instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "db_op_put{quantile=\"$quantile\",instance=~\"$instance\"}"
    },
    {
     "expr": "db_op_put_current{quantile=\"$quantile\",instance=~\"$instance\"}"
    },
    {
     "expr": "db_op_put_no_overwrite{quantile=\"$quantile\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "db.Get() latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "db_get{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "get: {{quantile}}, {{instance}}"
    }
   ]
  },
  {
   "title": "AutoDupsort Call/Sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "db_op_set{quantile=\"$quantile\",instance=~\"$instance\"}"
    },
    {
     "expr": "db_op_set_range{quantile=\"$quantile\",instance=~\"$instance\"}"
    },
    {
     "expr": "db_op_get{quantile=\"$quantile\",instance=~\"$instance\"}"
    },
    {
     "expr": "db_op_get_both{quantile=\"$quantile\",instance=~\"$instance\"}"
    },
    {
     "expr": "db_op_get_both_range{quantile=\"$quantile\",instance=~\"$instance\"}"
    },
    {
     "expr": "db_op_put{quantile=\"$quantile\",instance=~\"$instance\"}"
    },
    {
     "expr": "db_op_put_current{quantile=\"$quantile\",instance=~\"$instance\"}"
    },
    {
     "expr": "db_op_put_no_overwrite{quantile=\"$quantile\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "AutoDupsort Put latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "lmdb_put_direct{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "lmdb_put_direct: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_put_direct{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_direct: {{quantile}}, {{instance}}"
    },
    {
     "expr": "lmdb_put_both_range{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "lmdb_put_both_range: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_put_both_range{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_both_range: {{quantile}}, {{instance}}"
    },
    {
     "expr": "lmdb_seek_exact{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "lmdb_seek_exact: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_seek_exact{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_seek_exact: {{quantile}}, {{instance}}"
    },
    {
     "expr": "lmdb_put_no_overwrite{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "lmdb_put_no_overwrite: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_put_no_overwrite{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_no_overwrite: {{quantile}}, {{instance}}"
    },
    {
     "expr": "lmdb_put_upsert{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "lmdb_put_upsert: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_put_upsert{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_upsert: {{quantile}}, {{instance}}"
    },
    {
     "expr": "lmdb_put_current2{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "lmdb_put_current2: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_put_current2{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_current2: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_put_upsert2{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "lmdb_put_upsert2: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_put_upsert2{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_upsert2: {{quantile}}, {{instance}}"
    },
    {
     "expr": "lmdb_del_current{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "lmdb_put_current: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_del_current{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_del_current: {{quantile}}, {{instance}}"
    },
    {
     "expr": "lmdb_seek_exact2{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "lmdb_seek_exact2: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_seek_exact2{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_seek_exact2: {{quantile}}, {{instance}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(p2p_ingress{instance=~\"$instance\"}[1m])",
     "legendFormat": "ingress: {{instance}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "p2p_peers{instance=~\"$instance\"}",
     "legendFormat": "peers: {{instance}}"
    },
    {
     "expr": "rate(p2p_dials{instance=~\"$instance\"}[1m])",
     "legendFormat": "dials: {{instance}}"
    },
    {
     "expr": "rate(p2p_serves{instance=~\"$instance\"}[1m])",
     "legendFormat": "serves: {{instance}}"
    }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stage_headers{instance=~\"$instance\"}",
     "legendFormat": "Header: {{instance}}"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stage_headers{instance=~\"$instance\"}",
     "legendFormat": "blocks:{{instance}}"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "txpool_queued{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Local transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "txpool_local{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chain_head_header{instance=~\"$instance\"}",
     "legendFormat": "header: {{instance}}"
    },
    {
     "expr": "chain_head_receipt{instance=~\"$instance\"}",
     "legendFormat": "receipt: {{instance}}"
    },
    {
     "expr": "chain_head_block{instance=~\"$instance\"}",
     "legendFormat": "block: {{instance}}"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\"}",
     "legendFormat": "executable: {{instance}}"
    },
    {
     "expr": "txpool_queued{instance=~\"$instance\"}",
     "legendFormat": "gapped: {{instance}}"
    },
    {
     "expr": "txpool_local{instance=~\"$instance\"}",
     "legendFormat": "local: {{instance}}"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(txpool_valid{instance=~\"$instance\"}[1m])",
     "legendFormat": "valid: {{instance}}"
    },
    {
     "expr": "rate(txpool_invalid{instance=~\"$instance\"}[1m])",
     "legendFormat": "invalid: {{instance}}"
    },
    {
     "expr": "rate(txpool_underpriced{instance=\"$instance\"}[1m])",
     "legendFormat": "underpriced"
    },
    {
     "expr": "rate(txpool_pending_discard{instance=\"$instance\"}[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace{instance=\"$instance\"}[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{instance=\"$instance\"}[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds{instance=\"$instance\"}[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped nofunds"
    }
   ]
  },
  {
   "title": "Private api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    {
     "title": "gRPC call, error rates ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (grpc_service, grpc_method, instance) (rate(grpc_server_started_total{instance=~\"$instance\"}[1m]))",
       "legendFormat": "Calls: {{grpc_service}}.{{grpc_method}}, {{instance}}"
      },
      {
       "expr": "sum by (grpc_service, grpc_method, instance) (rate(grpc_server_handled_total{instance=~\"$instance\",grpc_code!=\"OK\"}[1m])) ",
       "legendFormat": "Errors: {{grpc_service}}.{{grpc_method}}, {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}